version: '3.3'

services:
  postgres:
    image: 'postgres:latest'
    volumes:
      - data:/var/lib/postgresql/data
      - "./sql/migrate-up.sql:/docker-entrypoint-initdb.d/migrate-up.sql"
    restart: always

    networks:
      - hosts
    environment:
      POSTGRES_DB: avito
      POSTGRES_USER: server
      POSTGRES_PASSWORD: M5F3wWtFxkQ8Ra4n
  server:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    environment:
      ARGS: -config docker.toml
    networks:
      - hosts
networks:
  hosts:
    driver: "bridge"
volumes:
  data: