version: '3.3'

services:
  mysql:
    image: mysql:latest
    volumes:
      - "./.mysql-data/db:/var/lib/mysql"
      - "./sql/migrate-up.sql:/docker-entrypoint-initdb.d/migrate-up.sql"
    restart: always

    networks:
      - hosts
    environment:
      MYSQL_ROOT_PASSWORD: rootpw
      MYSQL_DATABASE: avito
      MYSQL_USER: server
      MYSQL_PASSWORD: M5F3wWtFxkQ8Ra4n
  server:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - mysql
    environment:
      ARGS: -config docker.toml
    networks:
      - hosts
networks:
  hosts:
    driver: "bridge"