[Postgres]
User = "server"
Pass = "M5F3wWtFxkQ8Ra4n"
DbName = "avito"
IP = "127.0.0.1"
Port = "5432"
Protocol = "tcp"

[Host]
Port = "8080"
Key = "cert/localhost.key"
Cert = "cert/localhost.crt"


[Exchanger]
Skip=true
Load=false
Every=120
Endpoint="https://free.currconv.com/api/v7/"
Key="b904b50e29877e8c38e0"
Base=["EUR","USD"]