[Postgres]
User = "server"
Pass = "M5F3wWtFxkQ8Ra4n"
DbName = "avito"
IP = "postgres"
Port = "5432"
Protocol = "tcp"

[Host]
Port = "8080"

[Exchanger]
Skip=true
Every=120
Endpoint="https://free.currconv.com/api/v7/convert"
Key="b904b50e29877e8c38e0"
Base=["EUR","USD"]