[MySQL]
Login = "server"
Pass = "M5F3wWtFxkQ8Ra4n"
DbName = "avito"
IP = "mysql"
Port = "3306"
Protocol = "tcp"

[Host]
Port = "8080"

[Exchanger]
Skip=false
Every=120
Endpoint="https://free.currconv.com/api/v7/convert"
Key="b904b50e29877e8c38e0"
Bases=["EUR","USD"]